### ISSUE TITLE
PrimaryKeyRelatedField replacement

### ISSUE THREAD

**Issue by BezBartek** [BezBartek/restdantic#4]
**Required interface:**
```python
class SomeModel(BaseModel):
    related_field: RelatedModel = RESTDanticRelatedKeyField(alias="application_id", queryset=RelatedModel.objects.all())
```

**Comment by dominikbak** [comment]
@BezBartek

For the purpose of easier differentiation between Django models and Pydantic models, i would call the Pydantic ones Schemas, so in your example

```
class SomeModelSchema(BaseModel):
    related_field: RelatedModel = RESTDanticRelatedKeyField(alias="application_id", queryset=RelatedModel.objects.all())
```

But I think that the type here should be 
```
related_field: int = RESTDanticRelatedKeyField(...)
```
or even, what will be easier to accomplish
```
related_field: RESTDanticRelatedKeyField = Field(...)
```
I think the schema should represent what we expect to be passed there, not what it returns??

To sum up, I propose:
```
related_field: KeyRelatedField = Field(lookup="whatever", queryset=RelatedModel.objects.all())
```
which is working more or less as expected. I will cleanup my code a bit and submit PR

EDIT: I thought it through, and the above does not make sense. Please disregard

**Comment by BezBartek** [comment]
#5 closed with.
